name: CampfireBuff
version: 1.2
api-version: 1.13
description: Few buffs if you right click with named papers on a Campfire.
author: [AlaDyn172]
main: ro.andreielvis.campfirebuff.Main

commands:

permissions: